// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvSkhRRLm4mO73BVSwlbzax9Og6sQPxvk',
    appId: '1:92205599641:web:44fcd5e6cedc8b12c0a108',
    messagingSenderId: '92205599641',
    projectId: 'apna-vaidya-task',
    authDomain: 'apna-vaidya-task.firebaseapp.com',
    storageBucket: 'apna-vaidya-task.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAObACqXvKaGq8iBKUISdk6WscyxMGj0W0',
    appId: '1:92205599641:ios:c02208804c402e17c0a108',
    messagingSenderId: '92205599641',
    projectId: 'apna-vaidya-task',
    storageBucket: 'apna-vaidya-task.appspot.com',
    iosBundleId: 'com.example.apnaVaidyaTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvSkhRRLm4mO73BVSwlbzax9Og6sQPxvk',
    appId: '1:92205599641:web:bdc2fe5ce649036ec0a108',
    messagingSenderId: '92205599641',
    projectId: 'apna-vaidya-task',
    authDomain: 'apna-vaidya-task.firebaseapp.com',
    storageBucket: 'apna-vaidya-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAObACqXvKaGq8iBKUISdk6WscyxMGj0W0',
    appId: '1:92205599641:ios:c02208804c402e17c0a108',
    messagingSenderId: '92205599641',
    projectId: 'apna-vaidya-task',
    storageBucket: 'apna-vaidya-task.appspot.com',
    iosBundleId: 'com.example.apnaVaidyaTask',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6KXJaYIS6RUBpfm0d-Pycoj9mj5rQFck',
    appId: '1:92205599641:android:16b4b350013008b2c0a108',
    messagingSenderId: '92205599641',
    projectId: 'apna-vaidya-task',
    storageBucket: 'apna-vaidya-task.appspot.com',
  );

}